networks:
  maild:
    # You nedd to create it by hand on the target docker host
    external: true

volumes:
  vmail: # mail storage
  spool: # temp mail storage
  clamav: # AV storage 
  amavis: # filtering storage
  spamassassin: # spam data 
  db: # database storage


services:
  db:
    image: ${IMG_DB}:${TAG}
    build: ./db/
    container_name: maild-db
    hostname: db
    restart: always
    env_file:
      - vars/db.env
      - vars/mua.env
      - .env
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - maild

  admin:
    image: ${IMG_ADMIN}:${TAG}
    build: ./admin/
    container_name: maild-admin
    hostname: admin
    restart: always
    # ports:
    #   - "8080:80"
    environment:
      POSTFIXADMIN_DB_PASSWORD: ${POSTGRES_PASSWORD}
    env_file:
      - vars/db.env
      - vars/admin.env
      - .env
    depends_on:
      - db
    networks:
      - maild
    logging: # See https://docs.docker.com/config/containers/logging/syslog/
      driver: syslog
      options:
        syslog-address: "unixgram:///dev/log"
    labels:
      # main traefik data
      - "traefik.enable=true"
      - "traefik.http.routers.mailadmin.rule=Host(`mailadmin.maild.cu`)"
      - "traefik.http.routers.mailadmin.entrypoints=websecure"

      # custom service (non default port)
      - "traefik.http.routers.mailadmin.service=mailadmin_custom_port"
      - "traefik.http.services.mailadmin_custom_port.loadbalancer.server.port=80"
      # auth and access control, you need to create the chain before activate this middleware
      #- "traefik.http.routers.mailadmin.middlewares=chain-no-auth-public@file"

  mua:
    image: ${IMG_MUA}:${TAG}
    build: ./mua/
    container_name: maild-mua
    hostname: mua
    restart: always
    # ports:
    #   - "80:80"
    env_file:
      - vars/db.env
      - vars/mua.env
      - .env
    depends_on:
      - mda
    networks:
      - maild
    logging: # See https://docs.docker.com/config/containers/logging/syslog/
      driver: syslog
      options:
        syslog-address: "unixgram:///dev/log"
    labels:
      # main traefik data
      - "traefik.enable=true"
      - "traefik.http.routers.webmail.rule=Host(`webmails.chagod.software`)"
      - "traefik.http.routers.webmail.entrypoints=websecure"
      # custom service (non default port)
      - "traefik.http.routers.webmail.service=webmail_custom_port"
      - "traefik.http.services.webmail_custom_port.loadbalancer.server.port=80"
      #  auth and access control
      - "traefik.http.routers.webmail.middlewares=chain-no-auth@file"

  mda:
    image: ${IMG_MDA}:${TAG}
    build: ./mda/
    domainname: ${DEFAULT_DOMAIN}
    container_name: maild-mda
    hostname: mda
    restart: always
    env_file:
      - vars/db.env
      - vars/mda.env
      - vars/ssl.env
      - .env
    ports:
      # - "110:110"
      # - "143:143"
      - "993:993"
      - "995:995"
      # - "4190"
      # - "12345"
    depends_on:
      - db
    volumes:
      - vmail:/home/vmail
      - /certs:/certs
      - spool:/var/spool/
    networks:
      - maild
    logging: # See https://docs.docker.com/config/containers/logging/syslog/
      driver: syslog
      options:
        syslog-address: "unixgram:///dev/log"

  mta:
    image: ${IMG_MTA}:${TAG}
    build: ./mta/
    container_name: maild-mta
    domainname: ${DEFAULT_DOMAIN}
    hostname: mta
    restart: always
    environment:
      MAILADMIN: ${MAIL_ADMIN_USER}@${DEFAULT_DOMAIN}
      DEBUG: 'true'
    env_file:
      - vars/mta.env
      - vars/ssl.env
      - vars/db.env
      - .env
    ports:
      - "25:25"
      - "465:465"
      - "587:587"
    volumes:
      - vmail:/home/vmail
      - /certs:/certs
      - spool:/var/spool/
    depends_on:
      - db
      - mda
      - amavis
      - clamav
    networks:
      - maild
    logging: # See https://docs.docker.com/config/containers/logging/syslog/
      driver: syslog
      options:
        syslog-address: "unixgram:///dev/log"

  clamav:
    image: ${IMG_CLAMAV}:${TAG}
    build: ./clamav/
    domainname: ${DEFAULT_DOMAIN}
    container_name: maild-clamav
    hostname: clamav
    restart: always
    # healthcheck:  # buiilt in the image
    #   test: [ "CMD", "./check.sh" ]
    #   interval: 60s
    #   retries: 3
    #   start_period: 120s
    env_file:
      - vars/clamav.env
    # ports:
    #   - "3310"
    volumes:
      - clamav:/var/lib/clamav
      - amavis:/var/lib/amavis
    networks:
      - maild
    logging: # See https://docs.docker.com/config/containers/logging/syslog/
      driver: syslog
      options:
        syslog-address: "unixgram:///dev/log"

  amavis:
    image: ${IMG_AMAVIS}:${TAG}
    build: ./amavis/
    domainname: ${DEFAULT_DOMAIN}
    container_name: maild-amavis
    hostname: amavis
    restart: always
    # healthcheck: # buiilt in the image
    #     test: ["CMD", "/check.sh"]
    #     interval: 60s
    #     retries: 3
    #     start_period: 120s
    env_file:
      - vars/amavis.env
      - vars/db.env
      - .env
    # ports:
    #   - "10024:10024"
    volumes:
      - amavis:/var/lib/amavis
      - spamassassin:/var/lib/spamassassin
      - spool:/var/spool/
    depends_on:
      - db
    networks:
      - maild
    logging: # See https://docs.docker.com/config/containers/logging/syslog/
      driver: syslog
      options:
        syslog-address: "unixgram:///dev/log"

  cron:
    image: ${IMG_CRON}:${TAG}
    build: ./cron/
    domainname: ${DEFAULT_DOMAIN}
    container_name: maild-cron
    hostname: cron
    restart: always
    env_file:
      - vars/db.env
      - vars/amavis.env
      - .env
    volumes:
      - /var/log:/var/log
      - vmail:/home/vmail
    depends_on:
      - db
    networks:
      - maild
    logging: # See https://docs.docker.com/config/containers/logging/syslog/
      driver: syslog
      options:
        syslog-address: "unixgram:///dev/log"
