#!/bin/sh

# Copyright 2007,2008 Duncan Findlay <duncf@debian.org>
# Copyright 2008-2019 Noah Meyerhans <noahm@debian.org>
# Copyright 2025 Pavel Milanes Costa <pavelmc@gmail.com> for MailAD

# This script does not do anything by default.  If you are using systemd,
# invoke "systemctl enable --now spamassassin-maintenance.timer" to enable
# spamassassin's daily maintenance systemd timer.  If you are not using
# systemd, or otherwise prefer to use cron for daily maintenance, set CRON=1
# in /etc/cron.daily/spamassassin

CRON=0

test -f /etc/default/spamassassin && . /etc/default/spamassassin

test -x /usr/bin/sa-update || exit 0
command -v gpg > /dev/null || exit 0

# Sleep for up to 3600 seconds if not running interactively
if [ ! -t 0 ]; then
    RANGE=3600
    number=`od -vAn -N2 -tu4 < /dev/urandom`
    number=`expr $number "%" $RANGE`
    sleep $number
fi

exec /usr/sbin/spamassassin-maint
